// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgJo9NjRTTszjdMYaG9S30wcMS_t0FdGE',
    appId: '1:77770642973:web:54b6d3c5dffffa4f01d8f4',
    messagingSenderId: '77770642973',
    projectId: 'findle-35fe7',
    authDomain: 'findle-35fe7.firebaseapp.com',
    storageBucket: 'findle-35fe7.firebasestorage.app',
    measurementId: 'G-8HC7TEJSH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABreZkyCuAfksSL_kvVQGUGfJ-bJ4wgF8',
    appId: '1:77770642973:android:0229e235f62d02de01d8f4',
    messagingSenderId: '77770642973',
    projectId: 'findle-35fe7',
    storageBucket: 'findle-35fe7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt7IK69q0e-kJ3KNWCs8HqeYvEx8nRiDM',
    appId: '1:77770642973:ios:d41aecfe9121985401d8f4',
    messagingSenderId: '77770642973',
    projectId: 'findle-35fe7',
    storageBucket: 'findle-35fe7.firebasestorage.app',
    iosBundleId: 'com.example.findle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt7IK69q0e-kJ3KNWCs8HqeYvEx8nRiDM',
    appId: '1:77770642973:ios:d41aecfe9121985401d8f4',
    messagingSenderId: '77770642973',
    projectId: 'findle-35fe7',
    storageBucket: 'findle-35fe7.firebasestorage.app',
    iosBundleId: 'com.example.findle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgJo9NjRTTszjdMYaG9S30wcMS_t0FdGE',
    appId: '1:77770642973:web:1eb0596e110d5be301d8f4',
    messagingSenderId: '77770642973',
    projectId: 'findle-35fe7',
    authDomain: 'findle-35fe7.firebaseapp.com',
    storageBucket: 'findle-35fe7.firebasestorage.app',
    measurementId: 'G-0D0PRX2BLD',
  );
}
